server:
  port: 8888

spring:
  application:
    name: Gateway
  cloud:
    name: Gateway
    discovery:
      enabled: true
  main:
    web-application-type: reactive
eureka:
  instance:
    hostname: localhost
